// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeShop.Data;

namespace ResumeShop.Migrations
{
    [DbContext(typeof(EshopContext))]
    [Migration("20240228115146_SeedData Entering")]
    partial class SeedDataEntering
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ResumeShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "لوازم سامسونگ",
                            Name = "سامسونگ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "لوازم هواوی",
                            Name = "هواوی"
                        },
                        new
                        {
                            Id = 3,
                            Description = "لوازم شیایومی",
                            Name = "شیاومی"
                        },
                        new
                        {
                            Id = 4,
                            Description = "لوازم اپل",
                            Name = "اپل"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
